name: MintHygge
version: '${project.version}'
main: dk.shadow.minthygge.MintHygge
author: Shadow
description: MintHygge
commands:
  hygge:
    permission: "*"
    description: MintHygge
    usage: /<command>
    aliases: [mh]

